ScreenManager:
    LoginScreen:
    ViajeScreen:
    PendientesScreen:
    TarifaScreen:
    ViajeEnCursoScreen:

<LoginMDTextField@MDTextField>:
    fill_color: 1, 1, 1, 0.25
    text_color: 1, 1, 1, 1
    hint_text_color: 1, 1, 1, 0.8
    icon_right_color: 1, 1, 1, 1
    line_color_focus: 1, 1, 1, 1
    font_name: "Poppins"
    mode: "fill"

<LoginScreen>:
    name: "login"
    username: username.text
    password: password.text
    show_password: False #Variable para poder manejar el mostrar o ocultar la contrasena
    background_orange_color : 0.9686, 0.5765, 0.1176, 1 #Definimos el color para todo el fondo de la app
    font_white_color : 1, 1, 1, 1

    MDFloatLayout:
        md_bg_color: root.background_orange_color
        MDBoxLayout:
            orientation: 'vertical'
            spacing: "24dp"
            padding: "40dp"
            size_hint: 0.9, 0.7
            pos_hint: {"center_x": 0.5, "center_y": 0.5}
            Image:
                source: "assets/kooneex_logo.png"
                size_hint: (0.8, None)
                height: "150dp"
                allow_stretch: True
                keep_ratio: True
                pos_hint: {"center_x": 0.5}
            MDLabel:
                text: "Iniciar Sesión"
                halign: "center"
                valign: "middle"
                size_hint_y: None
                height: self.texture_size[1]
                font_name: "Poppins"
                bold: True
                font_style: "H5"
                theme_text_color: "Custom"
                text_color: root.font_white_color
            LoginMDTextField:
                id: username
                hint_text: "Usuario"
                icon_right: "account"
                
            LoginMDTextField:
                id: password
                hint_text: "Contraseña"
                password: not root.show_password  # cambia dinámicamente
                icon_right: "eye-off" if not root.show_password else "eye"
                on_icon_right: root.toggle_password_visibility()

            MDRaisedButton:
                text: "Ingresar"
                md_bg_color: 1, 1, 1, 1
                text_color: 0.9686, 0.5765, 0.1176, 1
                font_name: "Poppins"
                pos_hint: {"center_x": 0.5}
                on_release: root.login()
            MDLabel:
                id: mensaje_label
                text: root.mensaje
                halign: "center"
                theme_text_color: "Custom"
                text_color: root.font_white_color
                font_name: "Inter"

<ViajeScreen>:
    name: "viaje"
    MDFloatLayout:
        md_bg_color: 0.9686, 0.5765, 0.1176, 1  # #F7931E
        BoxLayout:
            orientation: 'vertical'
            padding: 10
            spacing: 10

            Label:
                text: "Solicitar Viaje"
                font_size: 22

            BoxLayout:
                id: solicitud_container
                orientation: 'vertical'
                spacing: 10

                TextInput:
                    id: origen_lat
                    hint_text: "Latitud de origen"
                    input_filter: "float"

                TextInput:
                    id: origen_lon
                    hint_text: "Longitud de origen"
                    input_filter: "float"

                TextInput:
                    id: destino_lat
                    hint_text: "Latitud de destino"
                    input_filter: "float"

                TextInput:
                    id: destino_lon
                    hint_text: "Longitud de destino"
                    input_filter: "float"
                
                TextInput:
                    id: cantidad_pasajeros
                    hint_text: "Cantidad de pasajeros"
                    input_filter: "int"

                Button:
                    text: "Solicitar viaje"
                    on_release:root.solicitar_viaje(origen_lat.text, origen_lon.text, destino_lat.text, destino_lon.text, cantidad_pasajeros.text)

            Label:
                id: mensaje_label
                text: ""
                color: 1, 1, 1, 1
                size_hint_y: None
                height: 80
                text_size: self.size
                halign: "center"
                valign: "middle"

<ViajeEnCursoScreen>:
    name: "viaje_en_curso"
    MDFloatLayout:
        md_bg_color: 0.9686, 0.5765, 0.1176, 1  # #F7931E
        BoxLayout:
            orientation: "vertical"
            padding: 20
            spacing: 10

            Label:
                id: info_label
                text: "Cargando información del viaje..."
                color: 1, 1, 1, 1

            Button:
                text: "Marcar como completado"
                background_color: 0, 1, 0, 1
                size_hint_y: None
                height: 50
                on_release: root.marcar_completado()

<ViajeEnCursoMotoScreen>:
    name: "viaje_en_curso_moto"
    MDFloatLayout:
        md_bg_color: 0.9686, 0.5765, 0.1176, 1  # #F7931E
        BoxLayout:
            orientation: "vertical"
            padding: 20
            spacing: 10

            Label:
                id: info_label
                text: "Cargando viaje en curso..."
                color: 1, 1, 1, 1

            Button:
                id: btn_iniciar
                text: "Iniciar viaje"
                background_color: 0, 1, 0, 1
                size_hint_y: None
                height: 50
                on_release: root.iniciar_viaje()
            
            Button:
                id: btn_completar
                text: "Marcar como completado"
                background_color: 0, 1, 0, 1
                size_hint_y: None
                height: 50
                on_release: root.marcar_completado()

<PendientesScreen>:
    MDFloatLayout:
        md_bg_color: 0.9686, 0.5765, 0.1176, 1  # #F7931E
        BoxLayout:
            orientation: "vertical"
            padding: 10
            spacing: 10

            Label:
                text: "Viajes Pendientes"
                font_size: 22
                bold: True
                size_hint_y: None
                height: 40
                color: 1, 1, 0, 1

            ScrollView:
                do_scroll_x: False
                do_scroll_y: True
                GridLayout:
                    id: viajes_container
                    cols: 1
                    size_hint_y: None
                    height: self.minimum_height
                    spacing: 10
            Label:
                id: notificacion_label
                text: ""
                size_hint_y: None
                height: 30
                color: 0, 1, 0, 1
                halign: "center"
        
<TarifaScreen>:
    MDFloatLayout:
        md_bg_color: 0.9686, 0.5765, 0.1176, 1  # #F7931E
        BoxLayout:
            orientation: "vertical"
            padding: 10
            spacing: 10

            Label:
                text: "Ofertas de Mototaxistas"
                font_size: 22
                bold: True
                size_hint_y: None
                height: 40
                color: 1, 1, 0, 1

            ScrollView:
                do_scroll_x: False
                do_scroll_y: True

                GridLayout:
                    id: tarifas_container
                    cols: 1
                    size_hint_y: None
                    height: self.minimum_height
                    spacing: 10

            Label:
                id: mensaje_tarifas
                text: ""
                size_hint_y: None
                height: 30
                color: 0, 1, 0, 1