<PendientesScreen>:
    BoxLayout:
        orientation: "vertical"

        RecycleView:
            id: rv_viajes
            viewclass: "PendienteItem"
            bar_width: dp(4)

            RecycleBoxLayout:
                orientation: "vertical"
                default_size: None, dp(260)
                default_size_hint: 1, None
                size_hint_y: None
                height: self.minimum_height
                spacing: dp(12)
