# Generated by Django 5.2.8 on 2026-01-24 21:10

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarifa', models.FloatField(blank=True, default=10.0, null=True)),
                ('comision', models.IntegerField(blank=True, default=1, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('mototaxista', 'Mototaxista'), ('pasajero', 'Pasajero')], default='pasajero', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Mototaxi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=50)),
                ('capacidad', models.PositiveIntegerField(default=4)),
                ('disponible', models.BooleanField(default=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('conductor', models.OneToOneField(limit_choices_to={'rol': 'mototaxista'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen_lat', models.FloatField()),
                ('origen_lon', models.FloatField()),
                ('destino_lat', models.FloatField()),
                ('destino_lon', models.FloatField()),
                ('cantidad_pasajeros', models.PositiveIntegerField(default=1)),
                ('referencia', models.CharField(max_length=100)),
                ('distancia_km', models.FloatField(blank=True, null=True)),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('costo_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('en_curso', 'En curso'), ('completado', 'Completado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('mototaxista', models.ForeignKey(blank=True, limit_choices_to={'rol': 'mototaxista'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes_mototaxista', to=settings.AUTH_USER_MODEL)),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta')], default='efectivo', max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('viaje', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.viaje')),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tiempo_estimado', models.CharField(max_length=50)),
                ('aceptada', models.BooleanField(default=False)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('mototaxista', models.ForeignKey(limit_choices_to={'rol': 'mototaxista'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='core.viaje')),
            ],
            options={
                'ordering': ['-creada_en'],
            },
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['username'], name='core_usuari_usernam_f6d50a_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['rol'], name='core_usuari_rol_96920f_idx'),
        ),
        migrations.AddIndex(
            model_name='mototaxi',
            index=models.Index(fields=['disponible'], name='core_motota_disponi_7adade_idx'),
        ),
        migrations.AddIndex(
            model_name='mototaxi',
            index=models.Index(fields=['conductor'], name='core_motota_conduct_2cc3d9_idx'),
        ),
        migrations.AddIndex(
            model_name='mototaxi',
            index=models.Index(fields=['latitud', 'longitud'], name='core_motota_latitud_c8f47d_idx'),
        ),
        migrations.AddIndex(
            model_name='viaje',
            index=models.Index(fields=['pasajero', 'estado'], name='core_viaje_pasajer_252b1c_idx'),
        ),
        migrations.AddIndex(
            model_name='viaje',
            index=models.Index(fields=['mototaxista', 'estado'], name='core_viaje_mototax_0e07a1_idx'),
        ),
        migrations.AddIndex(
            model_name='viaje',
            index=models.Index(fields=['estado', 'creado_en'], name='core_viaje_estado_239d4b_idx'),
        ),
        migrations.AddIndex(
            model_name='viaje',
            index=models.Index(fields=['origen_lat', 'origen_lon'], name='core_viaje_origen__27569e_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['viaje'], name='core_pago_viaje_i_1f3f72_idx'),
        ),
        migrations.AddIndex(
            model_name='oferta',
            index=models.Index(fields=['mototaxista', 'aceptada'], name='core_oferta_mototax_670af4_idx'),
        ),
        migrations.AddIndex(
            model_name='oferta',
            index=models.Index(fields=['viaje', 'aceptada'], name='core_oferta_viaje_i_e02bc6_idx'),
        ),
        migrations.AddIndex(
            model_name='oferta',
            index=models.Index(fields=['creada_en'], name='core_oferta_creada__5761db_idx'),
        ),
    ]
