# Generated by Django 5.2.7 on 2025-10-31 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mototaxi',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mototaxi',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
