# Generated by Django 5.2.7 on 2025-10-31 07:56

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mototaxi_latitud_mototaxi_longitud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='completado',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='costo',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='mototaxi',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='origen',
        ),
        migrations.AddField(
            model_name='viaje',
            name='costo_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='viaje',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='viaje',
            name='destino_lat',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viaje',
            name='destino_lon',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viaje',
            name='distancia_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viaje',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('en_curso', 'En curso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='viaje',
            name='mototaxista',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'mototaxista'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes_mototaxista', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='viaje',
            name='origen_lat',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viaje',
            name='origen_lon',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='viaje',
            name='pasajero',
            field=models.ForeignKey(limit_choices_to={'rol': 'pasajero'}, on_delete=django.db.models.deletion.CASCADE, related_name='viajes_pasajero', to=settings.AUTH_USER_MODEL),
        ),
    ]
