# Generated by Django 5.2.7 on 2025-11-03 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_viaje_completado_remove_viaje_costo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='cantidad_pasajeros',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='costo_estimado',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='mototaxista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mototaxi'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='pasajero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to=settings.AUTH_USER_MODEL),
        ),
    ]
