# Generated by Django 5.2.7 on 2025-11-03 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_viaje_cantidad_pasajeros_alter_viaje_costo_estimado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='mototaxista',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'mototaxista'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes_mototaxista', to=settings.AUTH_USER_MODEL),
        ),
    ]
