# Generated by Django 5.2.7 on 2025-11-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_viaje_mototaxista'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='tarifa_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='viaje',
            name='tarifa_sugerida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('tarifa_sugerida', 'Tarifa sugerida'), ('aceptado', 'Aceptado'), ('en_curso', 'En curso'), ('completado', 'Completado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
    ]
