# Generated by Django 5.2.7 on 2025-11-06 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_viaje_estado_ofertatarifa'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OfertaTarifa',
            new_name='Oferta',
        ),
    ]
