# Generated by Django 5.2.7 on 2025-11-08 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_ofertatarifa_oferta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viaje',
            old_name='tarifa_final',
            new_name='costo_final',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='tarifa_sugerida',
        ),
        migrations.AlterField(
            model_name='viaje',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('en_curso', 'En curso'), ('completado', 'Completado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
    ]
