# Generated by Django 5.2.7 on 2025-11-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_tarifa_final_viaje_costo_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='costo_final',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
