# Generated by Django 5.2.7 on 2025-11-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_viaje_costo_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='tiempo_estimado',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='costo_estimado',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='costo_final',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
