# Generated by Django 5.2.7 on 2025-11-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_oferta_tiempo_estimado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='tiempo_estimado',
            field=models.CharField(max_length=50),
        ),
    ]
