# Generated by Django 5.2.7 on 2025-11-08 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_oferta_tiempo_estimado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='mototaxista',
            field=models.ForeignKey(limit_choices_to={'rol': 'mototaxista'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
