# Generated by Django 5.2.7 on 2025-11-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_oferta_mototaxista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='costo_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='costo_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
