# Generated by Django 5.2.8 on 2025-12-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0014_alter_viaje_costo_estimado_alter_viaje_costo_final'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oferta',
            options={'ordering': ['-creada_en']},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.AlterModelOptions(
            name='viaje',
            options={'ordering': ['-creado_en']},
        ),
        migrations.AddIndex(
            model_name='mototaxi',
            index=models.Index(fields=['disponible'], name='core_motota_disponi_7adade_idx'),
        ),
        migrations.AddIndex(
            model_name='mototaxi',
            index=models.Index(fields=['conductor'], name='core_motota_conduct_2cc3d9_idx'),
        ),
        migrations.AddIndex(
            model_name='mototaxi',
            index=models.Index(fields=['latitud', 'longitud'], name='core_motota_latitud_c8f47d_idx'),
        ),
        migrations.AddIndex(
            model_name='oferta',
            index=models.Index(fields=['mototaxista', 'aceptada'], name='core_oferta_mototax_670af4_idx'),
        ),
        migrations.AddIndex(
            model_name='oferta',
            index=models.Index(fields=['viaje', 'aceptada'], name='core_oferta_viaje_i_e02bc6_idx'),
        ),
        migrations.AddIndex(
            model_name='oferta',
            index=models.Index(fields=['creada_en'], name='core_oferta_creada__5761db_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['viaje'], name='core_pago_viaje_i_1f3f72_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['username'], name='core_usuari_usernam_f6d50a_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['rol'], name='core_usuari_rol_96920f_idx'),
        ),
        migrations.AddIndex(
            model_name='viaje',
            index=models.Index(fields=['pasajero', 'estado'], name='core_viaje_pasajer_252b1c_idx'),
        ),
        migrations.AddIndex(
            model_name='viaje',
            index=models.Index(fields=['mototaxista', 'estado'], name='core_viaje_mototax_0e07a1_idx'),
        ),
        migrations.AddIndex(
            model_name='viaje',
            index=models.Index(fields=['estado', 'creado_en'], name='core_viaje_estado_239d4b_idx'),
        ),
        migrations.AddIndex(
            model_name='viaje',
            index=models.Index(fields=['origen_lat', 'origen_lon'], name='core_viaje_origen__27569e_idx'),
        ),
    ]
