# Generated by Django 5.2.8 on 2026-01-13 23:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_oferta_options_alter_usuario_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='referencia',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
