# Generated by Django 5.2.8 on 2026-01-13 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_viaje_referencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='referencia',
        ),
    ]
