# Generated by Django 5.2.8 on 2026-01-13 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_viaje_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='referencia',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
