# Generated by Django 5.2.8 on 2026-01-14 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_tarifa'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifa',
            name='comision',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
