# Generated by Django 5.2.8 on 2026-01-14 05:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_tarifa_comision'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifa',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='creada_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
